# slight modification of https://github.com/r-hub/rhub-linux-builders/tree/master/fedora

# include a default value to avoid "InvalidDefaultArgInFrom" warning (ref. https://docs.docker.com/reference/build-checks/invalid-default-arg-in-from/)
ARG FEDORA_VERSION=40

FROM fedora:$FEDORA_VERSION

RUN echo "$FEDORA_VERSION"

## Copy 'checkbashisms' (as a local copy from devscripts package)
COPY checkbashisms /usr/local/bin

# Install shadow-utils to ensure useradd is available
RUN dnf -y update && dnf -y install shadow-utils

## Set a default user. Available via runtime flag
RUN useradd docker

RUN dnf update -y
RUN dnf install -y \
	gcc-gfortran \
	less \
	ca-certificates \
	curl \
	java-1.8.0-openjdk \
	bzip2-devel \
	cairo-devel \
	ghostscript \
	libcurl-devel \
	libicu-devel \
	libjpeg-turbo-devel \
	pango-devel \
	pcre-devel \
	libpng-devel \
	readline-devel \
	libtiff-devel \
	libX11-devel \
	libXt-devel \
	subversion \
	tcl-devel \
	texinfo \
	texlive-latex \
	texlive-collection-fontsextra \
	texlive-scheme-basic \
	tk-devel \
	unzip \
	xorg-x11-proto-devel \
	findutils \
	make \
	texinfo-tex \
	xz-devel \
	zlib-devel \
	libXmu-devel \
	tar \
	texlive-ec \
	texlive-parskip \
	texlive-collection-fontsrecommended \
	which \
	xorg-x11-server-Xvfb

RUN dnf install -y \
	dnf-plugins-core

RUN dnf install -y glibc-langpack-en.x86_64

RUN dnf install -y valgrind

RUN dnf install -y qpdf

RUN dnf install -y aspell aspell-en

RUN dnf install -y file

RUN dnf install -y xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi

RUN dnf update -y

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
