# slight modification of https://github.com/r-hub/rhub-linux-builders/tree/master/fedora-clang

FROM mlampros/fedorar:latest

RUN dnf update -y

# References (latest clang version):
# https://discussion.fedoraproject.org/t/fedora-llvm-team-llvm-snapshots-big-merge-20231202/97999
# https://github.com/kwk/llvm-daily-fedora-rpms

RUN dnf5 install -y 'dnf5-command(copr)'
RUN dnf5 copr enable -y @fedora-llvm-team/llvm-snapshots
RUN dnf5 install -y \
	llvm \
	clang \
	compiler-rt
