# slight modification of https://github.com/r-hub/rhub-linux-builders/tree/master/fedora

# include a default value to avoid "InvalidDefaultArgInFrom" warning (ref. https://docs.docker.com/reference/build-checks/invalid-default-arg-in-from/)
ARG FEDORA_VERSION=40

FROM fedora:$FEDORA_VERSION

RUN echo "$FEDORA_VERSION"

## Copy 'checkbashisms' (as a local copy from devscripts package)
COPY checkbashisms /usr/local/bin

# Install shadow-utils to ensure useradd is available
RUN dnf -y update && dnf -y install shadow-utils

## Set a default user. Available via runtime flag
RUN useradd docker

RUN dnf update -y

# Enable all repositories and clean dnf cache
RUN dnf install -y dnf-plugins-core && \
    dnf clean all && \
    dnf makecache

# Install packages in smaller groups to identify problematic ones
# Basic tools group
RUN dnf install -y \
    gcc-gfortran \
    less \
    ca-certificates \
    curl \
    findutils \
    make \
    tar \
    which \
    file \
    unzip

# Java
RUN dnf install -y java-1.8.0-openjdk || echo "Java 1.8 not available, trying newer version" && \
    dnf install -y java-latest-openjdk

# Development libraries - part 1
RUN dnf install -y \
    bzip2-devel \
    libcurl-devel \
    libicu-devel \
    pcre-devel \
    libpng-devel \
    readline-devel \
    zlib-devel \
    xz-devel

# Development libraries - part 2
RUN dnf install -y \
    cairo-devel \
    libjpeg-turbo-devel \
    pango-devel \
    libtiff-devel \
    libX11-devel \
    libXt-devel \
    libXmu-devel

# Version control and dev tools
RUN dnf install -y \
    subversion \
    tcl-devel \
    tk-devel \
    ghostscript \
    xorg-x11-proto-devel

# TeX packages
RUN dnf install -y \
    texinfo \
    texinfo-tex \
    texlive-latex || echo "Package not found, trying alternatives" && \
    dnf install -y texlive-scheme-basic

# Additional TeX packages - try each separately
RUN dnf install -y texlive-collection-fontsextra || echo "texlive-collection-fontsextra not available"
RUN dnf install -y texlive-scheme-basic || echo "texlive-scheme-basic not available"
RUN dnf install -y texlive-ec || echo "texlive-ec not available"
RUN dnf install -y texlive-parskip || echo "texlive-parskip not available"
RUN dnf install -y texlive-collection-fontsrecommended || echo "texlive-collection-fontsrecommended not available"

# X11 related
RUN dnf install -y \
    xorg-x11-server-Xvfb \
    xorg-x11-fonts-100dpi \
    xorg-x11-fonts-75dpi || echo "Some X11 packages might not be available"

# Additional tools
RUN dnf install -y \
    glibc-langpack-en.x86_64 \
    valgrind \
    qpdf \
    aspell \
    aspell-en

RUN dnf update -y

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
